[phases.setup]
nixPkgs = ["...", "python311Packages.supervisor"]

[phases.build]
cmds = [
    "mkdir -p /etc/supervisor/conf.d/",
    "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
    "cp /assets/supervisord.conf /etc/supervisord.conf",
    "chmod +x /assets/extra.sh",
    "...",
    "/assets/extra.sh",
]


[staticAssets]
"extra.sh" = '''
#!/bin/bash

# Enable OPcache (does this even work?)
PHP_INI_PATH=$(php -i | grep '/php.ini' | awk '{print $6}')
echo 'php path found: ' $PHP_INI_PATH
# Enable opcache by adding to the bottom of the php.ini
echo opcache.memory_consumption=256 >> "$PHP_INI_PATH"
echo opcache.interned_strings_buffer=64 >> "$PHP_INI_PATH"
echo opcache.max_accelerated_files=32531 >> "$PHP_INI_PATH"
echo opcache.validate_timestamps=0 >> "$PHP_INI_PATH"
echo opcache.enable_cli=1 >> "$PHP_INI_PATH"
'''

"supervisord.conf" = '''
[unix_http_server]
file=/assets/supervisor.sock

[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/assets/supervisord.pid
nodaemon=false
silent=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///assets/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
'''

"worker-laravel.conf" = '''
[program:worker-laravel]
process_name=%(program_name)s_%(process_num)02d
command=bash -c 'exec php /app/artisan horizon'
autostart=true
autorestart=true
startsecs=0
stopwaitsecs=3600
stdout_logfile=/app/storage/logs/worker-laravel.log
stderr_logfile=/app/storage/logs/worker-laravel.log
'''
